# **PART A**

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("garments_worker_productivity.csv")

In [3]:
df.head()

,date,quarter,department,day,team,targeted_productivity,smv,wip,over_time,incentive,idle_time,idle_men,no_of_style_change,no_of_workers,actual_productivity
0,1/1/2015,Quarter1,sweing,Thursday,8,0.80,26.16,1108.0,7080,98,0.0,0,0,59.0,0.940725
1,1/1/2015,Quarter1,finishing,Thursday,1,0.75,3.94,NaN,960,0,0.0,0,0,8.0,0.886500
2,1/1/2015,Quarter1,sweing,Thursday,11,0.80,11.41,968.0,3660,50,0.0,0,0,30.5,0.800570
3,1/1/2015,Quarter1,sweing,Thursday,12,0.80,11.41,968.0,3660,50,0.0,0,0,30.5,0.800570
4,1/1/2015,Quarter1,sweing,Thursday,6,0.80,25.90,1170.0,1920,50,0.0,0,0,56.0,0.800382

In [4]:
df.shape

(1197, 15)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1197 entries, 0 to 1196
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   date                   1197 non-null   object
 1   quarter                1197 non-null   object
 2   department             1197 non-null   object
 3   day                    1197 non-null   object
 4   team                   1197 non-null   int64
 5   targeted_productivity  1197 non-null   float64
 6   smv                    1197 non-null   float64
 7   wip                    691 non-null    float64
 8   over_time              1197 non-null   int64
 9   incentive              1197 non-null   int64
 10  idle_time              1197 non-null   float64
 11  idle_men               1197 non-null   int64
 12  no_of_style_change     1197 non-null   int64
 13  no_of_workers          1197 non-null   float64
 14  actual_productivity    1197 non-null   float64
dtypes: float64(6), int64(5), object(4)
memory usage: 140.4+ KB

In [6]:
df.describe()

,team,targeted_productivity,smv,wip,over_time,incentive,idle_time,idle_men,no_of_style_change,no_of_workers,actual_productivity
count,1197.000000,1197.000000,1197.000000,691.000000,1197.000000,1197.000000,1197.000000,1197.000000,1197.000000,1197.000000,1197.000000
mean,6.426901,0.729632,15.062172,1190.465991,4567.460317,38.210526,0.730159,0.369256,0.150376,34.609858,0.735091
std,3.463963,0.097891,10.943219,1837.455001,3348.823563,160.182643,12.709757,3.268987,0.427848,22.197687,0.174488
min,1.000000,0.070000,2.900000,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.233705
25%,3.000000,0.700000,3.940000,774.500000,1440.000000,0.000000,0.000000,0.000000,0.000000,9.000000,0.650307
50%,6.000000,0.750000,15.260000,1039.000000,3960.000000,0.000000,0.000000,0.000000,0.000000,34.000000,0.773333
75%,9.000000,0.800000,24.260000,1252.500000,6960.000000,50.000000,0.000000,0.000000,0.000000,57.000000,0.850253
max,12.000000,0.800000,54.560000,23122.000000,25920.000000,3600.000000,300.000000,45.000000,2.000000,89.000000,1.120437

In [7]:
df.columns

Index(['date', 'quarter', 'department', 'day', 'team', 'targeted_productivity',
       'smv', 'wip', 'over_time', 'incentive', 'idle_time', 'idle_men',
       'no_of_style_change', 'no_of_workers', 'actual_productivity'],
      dtype='object')

In [8]:
df.isnull().sum()

date                       0
quarter                    0
department                 0
day                        0
team                       0
targeted_productivity      0
smv                        0
wip                      506
over_time                  0
incentive                  0
idle_time                  0
idle_men                   0
no_of_style_change         0
no_of_workers              0
actual_productivity        0
dtype: int64

In [9]:
(df.isnull().sum() / len(df) * 100).sort_values(ascending=False)

wip                      42.272348
quarter                   0.000000
date                      0.000000
day                       0.000000
team                      0.000000
targeted_productivity     0.000000
department                0.000000
smv                       0.000000
over_time                 0.000000
incentive                 0.000000
idle_time                 0.000000
idle_men                  0.000000
no_of_style_change        0.000000
no_of_workers             0.000000
actual_productivity       0.000000
dtype: float64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.select_dtypes(include="object").columns

Index(['date', 'quarter', 'department', 'day'], dtype='object')

In [12]:
for col in df.select_dtypes(include="object").columns:
    print("\n", col)
    print(df[col].unique())

 date
['1/1/2015' '1/3/2015' '1/4/2015' '1/5/2015' '1/6/2015' '1/7/2015'
 '1/8/2015' '1/10/2015' '1/11/2015' '1/12/2015' '1/13/2015' '1/14/2015'
 '1/15/2015' '1/17/2015' '1/18/2015' '1/19/2015' '1/20/2015' '1/21/2015'
 '1/22/2015' '1/24/2015' '1/25/2015' '1/26/2015' '1/27/2015' '1/28/2015'
 '1/29/2015' '1/31/2015' '2/1/2015' '2/2/2015' '2/3/2015' '2/4/2015'
 '2/5/2015' '2/7/2015' '2/8/2015' '2/9/2015' '2/10/2015' '2/11/2015'
 '2/12/2015' '2/14/2015' '2/15/2015' '2/16/2015' '2/17/2015' '2/18/2015'
 '2/19/2015' '2/22/2015' '2/23/2015' '2/24/2015' '2/25/2015' '2/26/2015'
 '2/28/2015' '3/1/2015' '3/2/2015' '3/3/2015' '3/4/2015' '3/5/2015'
 '3/7/2015' '3/8/2015' '3/9/2015' '3/10/2015' '3/11/2015']

 quarter
['Quarter1' 'Quarter2' 'Quarter3' 'Quarter4' 'Quarter5']

 department
['sweing' 'finishing ' 'finishing']

 day
['Thursday' 'Saturday' 'Sunday' 'Monday' 'Tuesday' 'Wednesday']

In [13]:
df.select_dtypes(include=np.number).columns

Index(['team', 'targeted_productivity', 'smv', 'wip', 'over_time', 'incentive',
       'idle_time', 'idle_men', 'no_of_style_change', 'no_of_workers',
       'actual_productivity'],
      dtype='object')

In [14]:
df[["actual_productivity", "targeted_productivity"]].describe()

       actual_productivity  targeted_productivity
count          1197.000000            1197.000000
mean              0.735091               0.729632
std               0.174488               0.097891
min               0.233705               0.070000
25%               0.650307               0.700000
50%               0.773333               0.750000
75%               0.850253               0.800000
max               1.120437               0.800000

In [15]:
df[["actual_productivity", "targeted_productivity"]].head(10)

   actual_productivity  targeted_productivity
0             0.940725                   0.80
1             0.886500                   0.75
2             0.800570                   0.80
3             0.800570                   0.80
4             0.800382                   0.80
5             0.800125                   0.80
6             0.755167                   0.75
7             0.753683                   0.75
8             0.753098                   0.75
9             0.750428                   0.75

In [16]:
print("Number of teams:", df["team"].nunique())
print("Teams:", sorted(df["team"].unique()))

Number of teams: 12
Teams: [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12)]

In [17]:
y_reg = df["actual_productivity"]

In [18]:
X_reg = df.drop(columns=["actual_productivity"])

In [19]:
df["MeetsTarget"] = (
    df["actual_productivity"] >= df["targeted_productivity"]
).astype(int)

In [20]:
df["MeetsTarget"].value_counts()

MeetsTarget
1    875
0    322
Name: count, dtype: int64

In [21]:
df["MeetsTarget"].value_counts(normalize=True)

MeetsTarget
1    0.730994
0    0.269006
Name: proportion, dtype: float64

In [22]:
X_cls = df.drop(columns=["actual_productivity", "MeetsTarget"])

In [23]:
y_cls = df["MeetsTarget"]

In [24]:
print("Regression:")
print("X:", X_reg.shape)
print("y:", y_reg.shape)
print("\nClassification:")
print("X:", X_cls.shape)
print("y:", y_cls.shape)

Regression:
X: (1197, 14)
y: (1197,)

Classification:
X: (1197, 14)
y: (1197,)

In [25]:
X_reg = df.drop(columns=["actual_productivity", "MeetsTarget"])
y_reg = df["actual_productivity"]

In [26]:
X_reg = df.drop(columns=["actual_productivity", "MeetsTarget"])
y_reg = df["actual_productivity"]

X_cls = df.drop(columns=["actual_productivity", "MeetsTarget"])
y_cls = df["MeetsTarget"]

print("Regression:", X_reg.shape, y_reg.shape)
print("Classification:", X_cls.shape, y_cls.shape)

Regression: (1197, 14) (1197,)
Classification: (1197, 14) (1197,)

In [27]:
np.random.seed(42)

indices = np.arange(len(df))
np.random.shuffle(indices)

split_point = int(0.80 * len(df))

train_indices = indices[:split_point]
test_indices = indices[split_point:]

In [28]:
print("Total samples:", len(df))
print("Training samples:", len(train_indices))
print("Testing samples:", len(test_indices))

Total samples: 1197
Training samples: 957
Testing samples: 240

In [29]:
print("Overlap:", len(set(train_indices) & set(test_indices)))

Overlap: 0

In [30]:
X_reg_train = X_reg.iloc[train_indices]
X_reg_test = X_reg.iloc[test_indices]

y_reg_train = y_reg.iloc[train_indices]
y_reg_test = y_reg.iloc[test_indices]

In [31]:
X_cls_train = X_cls.iloc[train_indices]
X_cls_test = X_cls.iloc[test_indices]

y_cls_train = y_cls.iloc[train_indices]
y_cls_test = y_cls.iloc[test_indices]

In [32]:
print("REGRESSION")
print("X_train:", X_reg_train.shape)
print("X_test :", X_reg_test.shape)
print("y_train:", y_reg_train.shape)
print("y_test :", y_reg_test.shape)

print("\nCLASSIFICATION")
print("X_train:", X_cls_train.shape)
print("X_test :", X_cls_test.shape)
print("y_train:", y_cls_train.shape)
print("y_test :", y_cls_test.shape)

REGRESSION
X_train: (957, 14)
X_test : (240, 14)
y_train: (957,)
y_test : (240,)

CLASSIFICATION
X_train: (957, 14)
X_test : (240, 14)
y_train: (957,)
y_test : (240,)

In [33]:
np.save("train_indices.npy", train_indices)
np.save("test_indices.npy", test_indices)

In [34]:
train_indices_check = np.load("train_indices.npy")
test_indices_check = np.load("test_indices.npy")

print(np.array_equal(train_indices, train_indices_check))
print(np.array_equal(test_indices, test_indices_check))

True
True

In [35]:
categorical_features = ["date", "quarter", "department", "day", "team"]
numerical_features = ["targeted_productivity", "smv", "wip", "over_time", "incentive", "idle_time", "idle_men", "no_of_style_change", "no_of_workers"]

In [36]:
print("Categorical features:")
print(X_reg[categorical_features].dtypes)

print("\nNumerical features:")
print(X_reg[numerical_features].dtypes)

Categorical features:
date          object
quarter       object
department    object
day           object
team           int64
dtype: object

Numerical features:
targeted_productivity    float64
smv                      float64
wip                      float64
over_time                  int64
incentive                  int64
idle_time                float64
idle_men                   int64
no_of_style_change         int64
no_of_workers            float64
dtype: object

In [37]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

In [38]:
numeric_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())])

In [39]:
categorical_pipeline = Pipeline([
    ("encoder", OneHotEncoder(handle_unknown="ignore"))])

In [40]:
preprocessor = ColumnTransformer([
    ("num", numeric_pipeline, numerical_features),
    ("cat", categorical_pipeline, categorical_features)])

In [41]:
X_reg_train_processed = preprocessor.fit_transform(X_reg_train)
X_reg_test_processed = preprocessor.transform(X_reg_test)

In [42]:
print("Training shape:", X_reg_train_processed.shape)
print("Testing shape:", X_reg_test_processed.shape)

Training shape: (957, 94)
Testing shape: (240, 94)

In [43]:
print("Processed data type:", type(X_reg_train_processed))

Processed data type: <class 'scipy.sparse._csr.csr_matrix'>

In [44]:
print("Missing values after preprocessing:")
print(np.isnan(X_reg_train_processed.toarray()).sum())

Missing values after preprocessing:
0

In [45]:
print("Missing values in test data:")
print(np.isnan(X_reg_test_processed.toarray()).sum())

Missing values in test data:
0

In [46]:
print("Number of processed features:", X_reg_train_processed.shape[1])

Number of processed features: 94

In [47]:
feature_names = preprocessor.get_feature_names_out()
print("Number of feature names:", len(feature_names))
print(feature_names)

Number of feature names: 94
['num__targeted_productivity' 'num__smv' 'num__wip' 'num__over_time'
 'num__incentive' 'num__idle_time' 'num__idle_men'
 'num__no_of_style_change' 'num__no_of_workers' 'cat__date_1/1/2015'
 'cat__date_1/10/2015' 'cat__date_1/11/2015' 'cat__date_1/12/2015'
 'cat__date_1/13/2015' 'cat__date_1/14/2015' 'cat__date_1/15/2015'
 'cat__date_1/17/2015' 'cat__date_1/18/2015' 'cat__date_1/19/2015'
 'cat__date_1/20/2015' 'cat__date_1/21/2015' 'cat__date_1/22/2015'
 'cat__date_1/24/2015' 'cat__date_1/25/2015' 'cat__date_1/26/2015'
 'cat__date_1/27/2015' 'cat__date_1/28/2015' 'cat__date_1/29/2015'
 'cat__date_1/3/2015' 'cat__date_1/31/2015' 'cat__date_1/4/2015'
 'cat__date_1/5/2015' 'cat__date_1/6/2015' 'cat__date_1/7/2015'
 'cat__date_1/8/2015' 'cat__date_2/1/2015' 'cat__date_2/10/2015'
 'cat__date_2/11/2015' 'cat__date_2/12/2015' 'cat__date_2/14/2015'
 'cat__date_2/15/2015' 'cat__date_2/16/2015' 'cat__date_2/17/2015'
 'cat__date_2/18/2015' 'cat__date_2/19/2015' 'cat__date_2/2/2015'
 'cat__date_2/22/2015' 'cat__date_2/23/2015' 'cat__date_2/24/2015'
 'cat__date_2/25/2015' 'cat__date_2/26/2015' 'cat__date_2/28/2015'
 'cat__date_2/3/2015' 'cat__date_2/4/2015' 'cat__date_2/5/2015'
 'cat__date_2/7/2015' 'cat__date_2/8/2015' 'cat__date_2/9/2015'
 'cat__date_3/1/2015' 'cat__date_3/10/2015' 'cat__date_3/11/2015'
 'cat__date_3/2/2015' 'cat__date_3/3/2015' 'cat__date_3/4/2015'
 'cat__date_3/5/2015' 'cat__date_3/7/2015' 'cat__date_3/8/2015'
 'cat__date_3/9/2015' 'cat__quarter_Quarter1' 'cat__quarter_Quarter2'
 'cat__quarter_Quarter3' 'cat__quarter_Quarter4' 'cat__quarter_Quarter5'
 'cat__department_finishing' 'cat__department_finishing '
 'cat__department_sweing' 'cat__day_Monday' 'cat__day_Saturday'
 'cat__day_Sunday' 'cat__day_Thursday' 'cat__day_Tuesday'
 'cat__day_Wednesday' 'cat__team_1' 'cat__team_2' 'cat__team_3'
 'cat__team_4' 'cat__team_5' 'cat__team_6' 'cat__team_7' 'cat__team_8'
 'cat__team_9' 'cat__team_10' 'cat__team_11' 'cat__team_12']

In [48]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import time

In [49]:
linear_model = LinearRegression()

In [50]:
start_time = time.perf_counter()
linear_model.fit(X_reg_train_processed, y_reg_train)
training_time = time.perf_counter() - start_time
print("Training time:", training_time, "seconds")

Training time: 0.01479299000001788 seconds

In [51]:
start_time = time.perf_counter()
y_reg_pred = linear_model.predict(X_reg_test_processed)
prediction_time = time.perf_counter() - start_time
print("Prediction time:", prediction_time, "seconds")

Prediction time: 0.001423482999996395 seconds

In [52]:
mae = mean_absolute_error(y_reg_test, y_reg_pred)
print("MAE:", mae)

MAE: 0.1025316790616533

In [53]:
rmse = np.sqrt(mean_squared_error(y_reg_test, y_reg_pred))
print("RMSE:", rmse)

RMSE: 0.14208494703262664

In [54]:
r2 = r2_score(y_reg_test, y_reg_pred)
print("R²:", r2)

R²: 0.3449219341201477

In [55]:
regression_sklearn_results = {"Model": "Scikit-learn Linear Regression","MAE":mae,"RMSE": rmse,"R2": r2, "Training Time": training_time,"Prediction Time": prediction_time}
print(regression_sklearn_results)

{'Model': 'Scikit-learn Linear Regression', 'MAE': 0.1025316790616533, 'RMSE': np.float64(0.14208494703262664), 'R2': 0.3449219341201477, 'Training Time': 0.01479299000001788, 'Prediction Time': 0.001423482999996395}

In [56]:
comparison = pd.DataFrame({
    "Actual": y_reg_test.values,
    "Predicted": y_reg_pred})
comparison.head(10)

     Actual  Predicted
0  0.616250   0.790710
1  0.952020   0.813942
2  0.961785   0.826310
3  0.906667   0.868262
4  0.949982   0.854319
5  0.799976   0.730429
6  0.471108   0.690984
7  0.355534   0.711248
8  0.800129   0.716582
9  0.759228   0.772602

In [57]:
regression_sklearn_results

{'Model': 'Scikit-learn Linear Regression',
 'MAE': 0.1025316790616533,
 'RMSE': np.float64(0.14208494703262664),
 'R2': 0.3449219341201477,
 'Training Time': 0.01479299000001788,
 'Prediction Time': 0.001423482999996395}

In [58]:
X_cls_train_processed = preprocessor.fit_transform(X_cls_train)
X_cls_test_processed = preprocessor.transform(X_cls_test)

print("Training shape:", X_cls_train_processed.shape)
print("Testing shape:", X_cls_test_processed.shape)

Training shape: (957, 94)
Testing shape: (240, 94)

In [59]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import time

logistic_model = LogisticRegression(max_iter=1000)

# Training
start_time = time.perf_counter()
logistic_model.fit(X_cls_train_processed, y_cls_train)
classification_training_time = time.perf_counter() - start_time

# Prediction
start_time = time.perf_counter()
y_cls_pred = logistic_model.predict(X_cls_test_processed)
classification_prediction_time = time.perf_counter() - start_time

# Metrics
accuracy = accuracy_score(y_cls_test, y_cls_pred)
precision = precision_score(y_cls_test, y_cls_pred)
recall = recall_score(y_cls_test, y_cls_pred)
f1 = f1_score(y_cls_test, y_cls_pred)

classification_sklearn_results = {"Model": "Scikit-learn Logistic Regression","Accuracy": accuracy,"Precision": precision,"Recall": recall,
    "F1": f1, "Training Time": classification_training_time, "Prediction Time": classification_prediction_time}
print(classification_sklearn_results)

{'Model': 'Scikit-learn Logistic Regression', 'Accuracy': 0.7458333333333333, 'Precision': 0.775, 'Recall': 0.9064327485380117, 'F1': 0.8355795148247979, 'Training Time': 0.033663012999994635, 'Prediction Time': 0.0005209159999992607}

In [60]:
print("Training time:", classification_training_time)
print("Prediction time:", classification_prediction_time)
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1:", f1)

Training time: 0.033663012999994635
Prediction time: 0.0005209159999992607
Accuracy: 0.7458333333333333
Precision: 0.775
Recall: 0.9064327485380117
F1: 0.8355795148247979

# **PART B**

In [61]:
# Regression data
X_manual_train = X_reg.iloc[train_indices].copy()
X_manual_test = X_reg.iloc[test_indices].copy()

y_manual_train = y_reg.iloc[train_indices].copy()
y_manual_test = y_reg.iloc[test_indices].copy()

print("Training shape:", X_manual_train.shape)
print("Testing shape:", X_manual_test.shape)

Training shape: (957, 14)
Testing shape: (240, 14)

In [62]:
categorical_features = ["date","quarter", "department", "day", "team"]
numerical_features = ["targeted_productivity", "smv", "wip", "over_time", "incentive", "idle_time", "idle_men", "no_of_style_change", "no_of_workers"]

In [63]:
wip_median = X_manual_train["wip"].median()
print("Training WIP median:", wip_median)

Training WIP median: 1047.0

In [64]:
X_manual_train["wip"] = X_manual_train["wip"].fillna(wip_median)
X_manual_test["wip"] = X_manual_test["wip"].fillna(wip_median)

In [65]:
combined = pd.concat([X_manual_train[categorical_features], X_manual_test[categorical_features]],axis=0)
combined_encoded = pd.get_dummies(combined, columns=categorical_features, dtype=float)

In [66]:
X_manual_train_cat = combined_encoded.iloc[:len(X_manual_train)]
X_manual_test_cat = combined_encoded.iloc[len(X_manual_train):]

print("Categorical encoded training shape:", X_manual_train_cat.shape)
print("Categorical encoded testing shape:", X_manual_test_cat.shape)

Categorical encoded training shape: (957, 85)
Categorical encoded testing shape: (240, 85)

In [67]:
train_num = X_manual_train[numerical_features].copy()
test_num = X_manual_test[numerical_features].copy()

train_mean = train_num.mean()
train_std = train_num.std(ddof=0)

In [68]:
train_num_scaled = (train_num - train_mean) / train_std
test_num_scaled = (test_num - train_mean) / train_std

In [69]:
print(train_num_scaled.head())

     targeted_productivity       smv       wip  over_time  incentive  \
921              -1.334891  0.675402 -0.364292   0.131362  -0.251068
321               0.712862 -0.339269 -0.062960  -0.066664   0.091093
101               0.712862 -1.115784 -0.045068  -0.948777  -0.251068
920              -0.311015 -1.024536 -0.045068  -1.092795  -0.251068
58                0.712862 -1.115784 -0.045068  -1.092795  -0.251068

     idle_time  idle_men  no_of_style_change  no_of_workers
921  -0.063241 -0.112037            2.062620       0.326365
321  -0.063241 -0.112037           -0.338751      -0.169721
101  -0.063241 -0.112037           -0.338751      -1.206992
920  -0.063241 -0.112037           -0.338751      -1.206992
58   -0.063241 -0.112037           -0.338751      -1.206992

In [70]:
X_manual_train_processed = pd.concat([train_num_scaled.reset_index(drop=True),X_manual_train_cat.reset_index(drop=True)],axis=1)
X_manual_test_processed = pd.concat([test_num_scaled.reset_index(drop=True),X_manual_test_cat.reset_index(drop=True)],axis=1)

In [71]:
X_manual_train_processed = X_manual_train_processed.to_numpy(dtype=float)
X_manual_test_processed = X_manual_test_processed.to_numpy(dtype=float)

y_manual_train = y_manual_train.to_numpy(dtype=float)
y_manual_test = y_manual_test.to_numpy(dtype=float)

In [72]:
# Add a column of 1s for the intercept
X_train_manual = np.column_stack([np.ones(X_manual_train_processed.shape[0]),X_manual_train_processed])
X_test_manual = np.column_stack([np.ones(X_manual_test_processed.shape[0]),X_manual_test_processed])

print("Training shape:", X_train_manual.shape)
print("Testing shape:", X_test_manual.shape)

Training shape: (957, 95)
Testing shape: (240, 95)

In [73]:
start_time = time.perf_counter()

# Normal Equation
XTX = X_train_manual.T @ X_train_manual
XTy = X_train_manual.T @ y_manual_train

beta = np.linalg.pinv(XTX) @ XTy
manual_training_time = time.perf_counter() - start_time

print("Number of coefficients:", len(beta))
print("Training time:", manual_training_time)

Number of coefficients: 95
Training time: 0.024277613999998948

In [74]:
start_time = time.perf_counter()
y_manual_pred = X_test_manual @ beta
manual_prediction_time = time.perf_counter() - start_time
print("Prediction time:", manual_prediction_time)
print("First 10 predictions:")
print(y_manual_pred[:10])

Prediction time: 0.0001794629999949393
First 10 predictions:
[0.79070805 0.8139411  0.82630768 0.86825913 0.85431798 0.73042783
 0.69098382 0.71124566 0.71657898 0.77260089]

In [75]:
# MAE
mae_manual = np.mean(np.abs(y_manual_test - y_manual_pred))

# RMSE
rmse_manual = np.sqrt(np.mean((y_manual_test - y_manual_pred) ** 2))

# R2
ss_res = np.sum((y_manual_test - y_manual_pred) ** 2)

ss_tot = np.sum((y_manual_test - np.mean(y_manual_test)) ** 2)
r2_manual = 1 - (ss_res / ss_tot)

print("Training time:", manual_training_time)
print("Prediction time:", manual_prediction_time)
print("MAE:", mae_manual)
print("RMSE:", rmse_manual)
print("R²:", r2_manual)

Training time: 0.024277613999998948
Prediction time: 0.0001794629999949393
MAE: 0.10253213607639537
RMSE: 0.14208537404321459
R²: 0.34491799667714285

In [76]:
regression_manual_results = {"Model": "Manual Linear Regression", "MAE": mae_manual, "RMSE": rmse_manual, "R2": r2_manual, "Training Time": manual_training_time,
"Prediction Time": manual_prediction_time}
print(regression_manual_results)

{'Model': 'Manual Linear Regression', 'MAE': np.float64(0.10253213607639537), 'RMSE': np.float64(0.14208537404321459), 'R2': np.float64(0.34491799667714285), 'Training Time': 0.024277613999998948, 'Prediction Time': 0.0001794629999949393}

In [77]:
X_cls_manual_train = X_cls.iloc[train_indices].copy()
X_cls_manual_test = X_cls.iloc[test_indices].copy()
y_cls_manual_train = y_cls.iloc[train_indices].to_numpy(dtype=float)
y_cls_manual_test = y_cls.iloc[test_indices].to_numpy(dtype=float)
print("Training shape:", X_cls_manual_train.shape)
print("Testing shape:", X_cls_manual_test.shape)

Training shape: (957, 14)
Testing shape: (240, 14)

In [78]:
wip_median_cls = X_cls_manual_train["wip"].median()
X_cls_manual_train["wip"] = X_cls_manual_train["wip"].fillna(wip_median_cls)
X_cls_manual_test["wip"] = X_cls_manual_test["wip"].fillna(wip_median_cls)

In [79]:
combined_cls = pd.concat([X_cls_manual_train[categorical_features], X_cls_manual_test[categorical_features]],axis=0)
combined_cls_encoded = pd.get_dummies(combined_cls, columns=categorical_features, dtype=float)
X_cls_train_cat = combined_cls_encoded.iloc[:len(X_cls_manual_train)]
X_cls_test_cat = combined_cls_encoded.iloc[len(X_cls_manual_train):]

In [80]:
train_num_cls = X_cls_manual_train[numerical_features].copy()
test_num_cls = X_cls_manual_test[numerical_features].copy()

train_mean_cls = train_num_cls.mean()
train_std_cls = train_num_cls.std(ddof=0)

train_num_cls_scaled = (train_num_cls - train_mean_cls) / train_std_cls
test_num_cls_scaled = (test_num_cls - train_mean_cls) / train_std_cls

In [81]:
X_cls_train_processed = pd.concat([train_num_cls_scaled.reset_index(drop=True), X_cls_train_cat.reset_index(drop=True)], axis=1)
X_cls_test_processed = pd.concat([test_num_cls_scaled.reset_index(drop=True), X_cls_test_cat.reset_index(drop=True)],axis=1)

X_cls_train_processed = X_cls_train_processed.to_numpy(dtype=float)
X_cls_test_processed = X_cls_test_processed.to_numpy(dtype=float)

print("Training shape:", X_cls_train_processed.shape)
print("Testing shape:", X_cls_test_processed.shape)

Training shape: (957, 94)
Testing shape: (240, 94)

In [82]:
X_cls_train_manual = np.column_stack([np.ones(X_cls_train_processed.shape[0]), X_cls_train_processed])
X_cls_test_manual = np.column_stack([np.ones(X_cls_test_processed.shape[0]), X_cls_test_processed])
print(X_cls_train_manual.shape)

(957, 95)

In [83]:
X_cls_manual_train = X_cls.iloc[train_indices].copy()
X_cls_manual_test = X_cls.iloc[test_indices].copy()

y_cls_manual_train = y_cls.iloc[train_indices].to_numpy(dtype=float)
y_cls_manual_test = y_cls.iloc[test_indices].to_numpy(dtype=float)

print("Training shape:", X_cls_manual_train.shape)
print("Testing shape:", X_cls_manual_test.shape)

Training shape: (957, 14)
Testing shape: (240, 14)

In [84]:
wip_median_cls = X_cls_manual_train["wip"].median()

X_cls_manual_train["wip"] = X_cls_manual_train["wip"].fillna(wip_median_cls)
X_cls_manual_test["wip"] = X_cls_manual_test["wip"].fillna(wip_median_cls)

In [85]:
combined_cls = pd.concat([X_cls_manual_train[categorical_features], X_cls_manual_test[categorical_features]], axis=0)
combined_cls_encoded = pd.get_dummies(combined_cls, columns=categorical_features, dtype=float)
X_cls_train_cat = combined_cls_encoded.iloc[:len(X_cls_manual_train)]
X_cls_test_cat = combined_cls_encoded.iloc[len(X_cls_manual_train):]

In [86]:
train_num_cls = X_cls_manual_train[numerical_features].copy()
test_num_cls = X_cls_manual_test[numerical_features].copy()

train_mean_cls = train_num_cls.mean()
train_std_cls = train_num_cls.std(ddof=0)

train_num_cls_scaled = (train_num_cls - train_mean_cls) / train_std_cls
test_num_cls_scaled = (test_num_cls - train_mean_cls) / train_std_cls

In [87]:
X_cls_train_processed = pd.concat([train_num_cls_scaled.reset_index(drop=True), X_cls_train_cat.reset_index(drop=True)],axis=1)
X_cls_test_processed = pd.concat([test_num_cls_scaled.reset_index(drop=True), X_cls_test_cat.reset_index(drop=True)],axis=1)

X_cls_train_processed = X_cls_train_processed.to_numpy(dtype=float)
X_cls_test_processed = X_cls_test_processed.to_numpy(dtype=float)

print("Processed training shape:", X_cls_train_processed.shape)
print("Processed testing shape:", X_cls_test_processed.shape)

Processed training shape: (957, 94)
Processed testing shape: (240, 94)

In [88]:
X_cls_train_manual = np.column_stack([np.ones(X_cls_train_processed.shape[0]),X_cls_train_processed])
X_cls_test_manual = np.column_stack([np.ones(X_cls_test_processed.shape[0]),X_cls_test_processed])

print("Final training shape:", X_cls_train_manual.shape)
print("Final testing shape:", X_cls_test_manual.shape)

Final training shape: (957, 95)
Final testing shape: (240, 95)

In [89]:
def sigmoid(z):
    z = np.clip(z, -500, 500)
    return 1 / (1 + np.exp(-z))

In [90]:
test_values = np.array([-2, -1, 0, 1, 2])
print(sigmoid(test_values))

[0.11920292 0.26894142 0.5        0.73105858 0.88079708]

In [91]:
weights = np.zeros(X_cls_train_manual.shape[1])
print("Number of weights:", len(weights))

Number of weights: 95

In [92]:
learning_rate = 0.01
iterations = 5000

start_time = time.perf_counter()
for i in range(iterations):
    # Calculate probabilities
    z = X_cls_train_manual @ weights
    probabilities = sigmoid(z)

    # Calculate gradient
    gradient = (X_cls_train_manual.T @(probabilities - y_cls_manual_train)) / len(y_cls_manual_train)

    # Update weights
    weights = weights - learning_rate * gradient

manual_classification_training_time = (time.perf_counter() - start_time)
print("Training time:", manual_classification_training_time)
print("Number of iterations:", iterations)

Training time: 0.3531231910000088
Number of iterations: 5000

In [93]:
start_time = time.perf_counter()
test_probabilities = sigmoid(X_cls_test_manual @ weights)
manual_classification_prediction_time = (time.perf_counter() - start_time)

print("Prediction time:", manual_classification_prediction_time)
print("First 10 probabilities:")
print(test_probabilities[:10])

Prediction time: 0.0003172109999809436
First 10 probabilities:
[0.59773528 0.69932405 0.7105637  0.57590511 0.91439928 0.89117705
 0.90366081 0.74000661 0.84309318 0.68884749]

In [94]:
threshold = 0.5
y_cls_manual_pred = (test_probabilities >= threshold).astype(int)

print("First 20 predictions:")
print(y_cls_manual_pred[:20])

First 20 predictions:
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]

In [95]:
TP = np.sum((y_cls_manual_test == 1) & (y_cls_manual_pred == 1))
TN = np.sum((y_cls_manual_test == 0) & (y_cls_manual_pred == 0))
FP = np.sum((y_cls_manual_test == 0) & (y_cls_manual_pred == 1))
FN = np.sum((y_cls_manual_test == 1) & (y_cls_manual_pred == 0))

print("TP:", TP)
print("TN:", TN)
print("FP:", FP)
print("FN:", FN)

TP: 161
TN: 14
FP: 55
FN: 10

In [96]:
accuracy_manual = (TP + TN) / (TP + TN + FP + FN)
precision_manual = TP / (TP + FP)
recall_manual = TP / (TP + FN)
f1_manual = (2 * precision_manual * recall_manual) / (precision_manual + recall_manual)

print("Accuracy:", accuracy_manual)
print("Precision:", precision_manual)
print("Recall:", recall_manual)
print("F1:", f1_manual)

Accuracy: 0.7291666666666666
Precision: 0.7453703703703703
Recall: 0.9415204678362573
F1: 0.8320413436692506

In [97]:
classification_manual_results = {"Model": "Manual Logistic Regression", "Accuracy": accuracy_manual, "Precision": precision_manual, "Recall": recall_manual,
"F1": f1_manual, "Training Time": manual_classification_training_time, "Prediction Time": manual_classification_prediction_time}
print(classification_manual_results)

{'Model': 'Manual Logistic Regression', 'Accuracy': np.float64(0.7291666666666666), 'Precision': np.float64(0.7453703703703703), 'Recall': np.float64(0.9415204678362573), 'F1': np.float64(0.8320413436692506), 'Training Time': 0.3531231910000088, 'Prediction Time': 0.0003172109999809436}

In [98]:
classification_manual_results

{'Model': 'Manual Logistic Regression',
 'Accuracy': np.float64(0.7291666666666666),
 'Precision': np.float64(0.7453703703703703),
 'Recall': np.float64(0.9415204678362573),
 'F1': np.float64(0.8320413436692506),
 'Training Time': 0.3531231910000088,
 'Prediction Time': 0.0003172109999809436}

# **PART C**

In [99]:
regression_comparison = pd.DataFrame([regression_sklearn_results,regression_manual_results])
regression_comparison

,Model,MAE,RMSE,R2,Training Time,Prediction Time
0,Scikit-learn Linear Regression,0.102532,0.142085,0.344922,0.014793,0.001423
1,Manual Linear Regression,0.102532,0.142085,0.344918,0.024278,0.000179

In [100]:
classification_comparison = pd.DataFrame([classification_sklearn_results, classification_manual_results])
classification_comparison

,Model,Accuracy,Precision,Recall,F1,Training Time,Prediction Time
0,Scikit-learn Logistic Regression,0.745833,0.77500,0.906433,0.835580,0.033663,0.000521
1,Manual Logistic Regression,0.729167,0.74537,0.941520,0.832041,0.353123,0.000317

In [101]:
regression_comparison.round(6)

,Model,MAE,RMSE,R2,Training Time,Prediction Time
0,Scikit-learn Linear Regression,0.102532,0.142085,0.344922,0.014793,0.001423
1,Manual Linear Regression,0.102532,0.142085,0.344918,0.024278,0.000179

In [102]:
classification_comparison.round(6)

,Model,Accuracy,Precision,Recall,F1,Training Time,Prediction Time
0,Scikit-learn Logistic Regression,0.745833,0.77500,0.906433,0.835580,0.033663,0.000521
1,Manual Logistic Regression,0.729167,0.74537,0.941520,0.832041,0.353123,0.000317

In [103]:
def train_logistic_regression(X, y, learning_rate=0.01, iterations=5000):
    weights = np.zeros(X.shape[1])
    start_time = time.perf_counter()

    for i in range(iterations):
        probabilities = sigmoid(X @ weights)
        gradient = (X.T @ (probabilities - y)) / len(y)
        weights -= learning_rate * gradient
    training_time = time.perf_counter() - start_time
    return weights, training_time

In [104]:
def predict_logistic_regression(X, weights, threshold=0.5):
    probabilities = sigmoid(X @ weights)
    predictions = (probabilities >= threshold).astype(int)
    return predictions

In [105]:
def classification_metrics_manual(y_true, y_pred):
    TP = np.sum((y_true == 1) & (y_pred == 1))
    TN = np.sum((y_true == 0) & (y_pred == 0))
    FP = np.sum((y_true == 0) & (y_pred == 1))
    FN = np.sum((y_true == 1) & (y_pred == 0))

    accuracy = (TP + TN) / (TP + TN + FP + FN)
    precision = TP / (TP + FP) if (TP + FP) > 0 else 0
    recall = TP / (TP + FN) if (TP + FN) > 0 else 0
    f1 = (2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0)
    return accuracy, precision, recall, f1

In [106]:
optimized_weights, optimized_training_time = train_logistic_regression(X_cls_train_manual, y_cls_manual_train, learning_rate=0.01, iterations=2000)
optimized_pred = predict_logistic_regression(X_cls_test_manual, optimized_weights)
optimized_metrics = classification_metrics_manual(y_cls_manual_test, optimized_pred)

print("Training time:", optimized_training_time)
print("Accuracy:", optimized_metrics[0])
print("Precision:", optimized_metrics[1])
print("Recall:", optimized_metrics[2])
print("F1:", optimized_metrics[3])

Training time: 0.13609483500002284
Accuracy: 0.7333333333333333
Precision: 0.7316017316017316
Recall: 0.9883040935672515
F1: 0.8407960199004975

In [107]:
learning_rates = [0.001, 0.005, 0.01, 0.05]
optimization_results = []

for lr in learning_rates:
    weights_lr, training_time_lr = train_logistic_regression(X_cls_train_manual, y_cls_manual_train, learning_rate=lr, iterations=2000)
    predictions_lr = predict_logistic_regression(X_cls_test_manual, weights_lr)
    accuracy_lr, precision_lr, recall_lr, f1_lr = (classification_metrics_manual(y_cls_manual_test,predictions_lr))
    optimization_results.append({"Learning Rate": lr,"Iterations": 2000,"Accuracy": accuracy_lr,"Precision": precision_lr,"Recall": recall_lr,"F1": f1_lr,
    "Training Time": training_time_lr})
optimization_df = pd.DataFrame(optimization_results)
optimization_df.round(6)

,Learning Rate,Iterations,Accuracy,Precision,Recall,F1,Training Time
0,0.001,2000,0.720833,0.718487,1.000000,0.836186,0.131422
1,0.005,2000,0.729167,0.724576,1.000000,0.840295,0.127665
2,0.010,2000,0.733333,0.731602,0.988304,0.840796,0.130466
3,0.050,2000,0.737500,0.752336,0.941520,0.836364,0.123759

In [108]:
def train_logistic_optimized(X, y, learning_rate=0.01, max_iterations=2000, tolerance=1e-7
):
    weights = np.zeros(X.shape[1])
    n = len(y)
    start_time = time.perf_counter()
    previous_loss = float("inf")

    for i in range(max_iterations):
        # Predictions
        probabilities = sigmoid(X @ weights)
        # Gradient
        gradient = (X.T @ (probabilities - y)) / n
        # Update weights
        weights -= learning_rate * gradient
        # Calculate loss
        probabilities = np.clip(sigmoid(X @ weights),1e-15,1 - 1e-15)
        loss = -np.mean(y * np.log(probabilities)+ (1 - y) * np.log(1 - probabilities))

        # Check convergence
        if abs(previous_loss - loss) < tolerance:
            break
        previous_loss = loss
    training_time = time.perf_counter() - start_time
    return weights, training_time, i + 1, loss

In [109]:
optimized_weights, optimized_time, iterations_used, final_loss = (train_logistic_optimized(X_cls_train_manual, y_cls_manual_train, learning_rate=0.01, max_iterations=2000,
tolerance=1e-7))
optimized_predictions = predict_logistic_regression(X_cls_test_manual, optimized_weights)
optimized_accuracy, optimized_precision, optimized_recall, optimized_f1 = (classification_metrics_manual(y_cls_manual_test, optimized_predictions))
print("Iterations used:", iterations_used)
print("Final loss:", final_loss)
print("Training time:", optimized_time)
print("Accuracy:", optimized_accuracy)
print("Precision:", optimized_precision)
print("Recall:", optimized_recall)
print("F1:", optimized_f1)

Iterations used: 2000
Final loss: 0.49859930731820234
Training time: 0.32252900000000295
Accuracy: 0.7333333333333333
Precision: 0.7316017316017316
Recall: 0.9883040935672515
F1: 0.8407960199004975

In [110]:
final_learning_rate = 0.01
final_iterations = 2000
start_time = time.perf_counter()
final_weights = np.zeros(X_cls_train_manual.shape[1])

for i in range(final_iterations):
    probabilities = sigmoid(X_cls_train_manual @ final_weights)
    gradient = (X_cls_train_manual.T @ (probabilities - y_cls_manual_train)) / len(y_cls_manual_train)
    final_weights -= final_learning_rate * gradient
final_optimized_training_time = (time.perf_counter() - start_time)

In [111]:
start_time = time.perf_counter()
final_probabilities = sigmoid(X_cls_test_manual @ final_weights)
final_predictions = (final_probabilities >= 0.5).astype(int)
final_optimized_prediction_time = (time.perf_counter() - start_time)

In [112]:
(final_accuracy, final_precision, final_recall, final_f1) = classification_metrics_manual(y_cls_manual_test, final_predictions)

In [113]:
final_optimized_results = {"Model": "Optimized Manual Logistic Regression", "Accuracy": final_accuracy, "Precision": final_precision, "Recall": final_recall,
"F1": final_f1, "Training Time": final_optimized_training_time, "Prediction Time": final_optimized_prediction_time}
print(final_optimized_results)

{'Model': 'Optimized Manual Logistic Regression', 'Accuracy': np.float64(0.7333333333333333), 'Precision': np.float64(0.7316017316017316), 'Recall': np.float64(0.9883040935672515), 'F1': np.float64(0.8407960199004975), 'Training Time': 0.1295474439999964, 'Prediction Time': 0.0003844549999882929}

# **FINAL COMPARISION**

In [114]:
final_regression_comparison = pd.DataFrame([regression_sklearn_results, regression_manual_results])
final_regression_comparison = final_regression_comparison.round(6)
final_regression_comparison

,Model,MAE,RMSE,R2,Training Time,Prediction Time
0,Scikit-learn Linear Regression,0.102532,0.142085,0.344922,0.014793,0.001423
1,Manual Linear Regression,0.102532,0.142085,0.344918,0.024278,0.000179

In [115]:
final_classification_comparison = pd.DataFrame([classification_sklearn_results, classification_manual_results, final_optimized_results])
final_classification_comparison = final_classification_comparison.round(6)
final_classification_comparison

,Model,Accuracy,Precision,Recall,F1,Training Time,Prediction Time
0,Scikit-learn Logistic Regression,0.745833,0.775000,0.906433,0.835580,0.033663,0.000521
1,Manual Logistic Regression,0.729167,0.745370,0.941520,0.832041,0.353123,0.000317
2,Optimized Manual Logistic Regression,0.733333,0.731602,0.988304,0.840796,0.129547,0.000384

In [116]:
optimization_summary = pd.DataFrame([{"Version": "Original Manual", "Learning Rate": 0.01, "Iterations": 5000, "Accuracy": 0.729167, "Precision": 0.745370, "Recall": 0.941520,
"F1": 0.832041, "Training Time": 0.749312}, {"Version": "Optimized Manual", "Learning Rate": 0.01, "Iterations": 2000, "Accuracy": final_accuracy, "Precision": final_precision,
"Recall": final_recall, "F1": final_f1, "Training Time": final_optimized_training_time}])
optimization_summary.round(6)

,Version,Learning Rate,Iterations,Accuracy,Precision,Recall,F1,Training Time
0,Original Manual,0.01,5000,0.729167,0.745370,0.941520,0.832041,0.749312
1,Optimized Manual,0.01,2000,0.733333,0.731602,0.988304,0.840796,0.129547